package:
  name: stomel
  version: 0.1.0

source:
  git_url: https://github.com/rustychris/stomel.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - rtree
    - python-cgal-bindings
    - gdal
    - shapely

build:
  number: 2

test:
  # Python imports
  imports:
    - stomel.tom

about:
  home: http://toblerity.github.com/rtree/
  license: GPLv2
  summary: 'Various scripts for ocean modeling including unstructured grid generation'

