package:
  name: gridgen-c
  version: 1.48

source:
 svn_url: http://gridgen-c.googlecode.com/svn/gridgen

about:
  home: https://code.google.com/p/gridgen-c
  license: MIT License
  summary: curvilinear orthogonal grid generation
build:
  number: 2

requirements:
  build:
   - gridutils
  run: 
   - gridutils

