package:
  name: rtree
  version: !!str 0.7.0

source:
  fn: Rtree-0.7.0.tar.gz
  url: https://pypi.python.org/packages/source/R/Rtree/Rtree-0.7.0.tar.gz
  md5: 84e75e5a9fdf7bd092435588be9084ac
  patches:
   - fixlibpath.patch

build:
  preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rtree = rtree:main
    #
    # Would create an entry point called rtree that calls rtree.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - patch
    - libspatialindex

  run:
    - python
    - setuptools
    - libspatialindex

test:
  # Python imports
  imports:
    - rtree
    - rtree.index

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://toblerity.github.com/rtree/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'R-Tree spatial index for Python GIS'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
