package:
  name: pythonmagick
  version: "0.9.12"

build:
  number: 0

source:
  fn: PythonMagick-0.9.12.tar.xz
  url: file:///lustre/scratch1/turquoise/pwolfram/stomel_install/conda-recipes/pythonmagick/PythonMagick-0.9.12.tar.xz
  sha256: 4b108324460aa497627a0fc2547f946253558cec3457a35f9f0e107adac833d0
  #git_url: https://github.com/ImageMagick/PythonMagick

# test:
#   commands:
#     - make check

# https://github.com/ImageMagick/PythonMagick/issues/2
requirements:
  build:
   - gcc
   - boost <1.60.0
   - python
   - imagemagick <7
   - pkg-config
   - libtool
  run:
   - boost <1.60.0
   - python
   - imagemagick <7

about:
  home: http://www.imagemagick.org/
  license: Apache
