package:
  name: gdal
  version: 1.11.2
 

source:
  # fn: gdal-1.10.1.tar.gz
  # url: http://download.osgeo.org/gdal/1.10.1/gdal-1.10.1.tar.gz
  # md5: 86b2c71a910d826a7fe6ebb43a532fb7

  url: http://download.osgeo.org/gdal/1.11.2/gdal-1.11.2.tar.gz
  fn: gdal-1.11.2.tar.gz
  patches:
    - relative_data.patch
build:
  number: 3

requirements:
  build:
    - python
    - proj4
    - hdf5
    - libnetcdf ==4.3.3.1
    - libpng
    - numpy 
    - libtiff
    - geos
    - curl
  run:
    - python
    - proj4
    - hdf5
    - libnetcdf ==4.3.3.1
    - libpng
    - numpy 
    - libtiff
    - geos
    - curl
test:
  files:
    - os1_hw.py
    - sites.dbf
    - sites.sbn
    - sites.sbx
    - sites.shp
    - sites.shx
  imports:
    - osgeo

about:
  home: http://www.gdal.org/
  license: MIT
