package: 
  name: cgal
  version: 4.3.0

source:
   fn: CGAL-4.3.tar.gz
   url: https://gforge.inria.fr/frs/download.php/32994/CGAL-4.3.tar.gz

about:
  home: http://www.cgal.org/
  license: GPL/LGPL
  summary: robust C++ implementation of geometric algorithms
build:
  number: 4
  string: 4

# needs boost - this is now in defaults.  the ioos boost is broken (and has been
# deprecated but still appears in the channel - 2015-08-02)

requirements:
  # it doesn't really require python, but maybe that will fix
  # the missing bin directory
  build:
   - boost 1.57.0
   - python
   - cmake 2.8.9
   - mpfr
   - gmp
  run:
   - boost 1.57.0
   - gmp
   - mpfr


