package: 
  name: cgal
  version: 4.3.0

source:
   fn: CGAL-4.3.tar.gz
   url: https://gforge.inria.fr/frs/download.php/32994/CGAL-4.3.tar.gz

about:
  home: http://www.cgal.org/
  license: GPL/LGPL
  summary: robust C++ implementation of geometric algorithms
build:
  number: 2
  string: 2wakari

# needs boost - one candidate is
# conda install -c https://conda.binstar.org/zwelch boost
# which means zwelch has to be in channels

requirements:
  # it doesn't really require python, but maybe that will fix
  # the missing bin directory
  build:
   - boost
   - python
   - cmake 2.8.9
   - mpfr
   - gmp
  run:
   - boost
   - gmp
   - mpfr


